### ISSUE TITLE
Testing service objects

### ISSUE THREAD

**Issue by kvhees** [kunif/OpenPOS-CSSO#1]

**Comment by kunif** [comment]
In fact, OPOS is basically part of a commercial product, and such test programs are proprietary and used internally by each vendor.
I don't know of any open source and free OPOS test system.

JavaPOS is still there, although its last update was 10 years ago.
https://github.com/ntsggr/JavaPOS-POStest-2

After that, the test application included in the POS for.NET SDK can indirectly call and use some OPOS. However, it also only supports a limited set of device categories and was last updated a long time ago.
https://www.microsoft.com/en-us/download/details.aspx?id=55758

**Comment by kvhees** [comment]
Thanks a lot for the information. We will contact one of the major vendors for a test system. 

Appreciate your fast reply!
