### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by kvhees** [kunif/OpenPOS-CSSO#2]

**Comment by kunif** [comment]
Unfortunately I haven't tried that.  
However, it may be possible to build by switching the following three reference DLLs described in the readme to those of CCO 1.15.  

>- The following DLL of OPOS-CCO ver1.16 and its PIA(Primary Interop Assembly) must be registered.  
>   - Opos_Interfaces.dll  
>   - Opos_Internals.dll  
>   - Opos_Constants.dll  

And for CCO 1.14.1, please use Opos_Constants.dll distributed from CCO 1.14.001 .msi installer or OPOS for .NET Assemblies 1.14.001, and Opos_Internals.dll and Opos_Interfaces.dll from this OposInternals repository.  
http://monroecs.com/oposccos_current.htm  
http://monroecs.com/posfordotnet/opos_dotnet.htm  

https://github.com/kunif/OposInternals  

Again, I haven't tried the above, so I don't have an answer if it works or not.

**Comment by kvhees** [comment]
Thank you for your swift response.

I will try compiling the binaries based on your instructions, and let you know the result on this thread.

If my target system is using OPOS 1.14.1, and I use a 1.16 compiled SO, will it work backwards with the system? 

Thank you very much.

**Comment by kunif** [comment]
The mechanism of COM (ComponentObjectModel) is loosely coupled, so if they are made in C++, they will work, but if .NET is involved, it may not work because it is sensitive to version differences.
Please try it.

**Comment by kvhees** [comment]
I was able to compile the skeleton service object (scanner) with 1.15, the build succeeded. 

When I register this using RegAsm, it's registered but it does not show up in the POS for .NET Test App. I was expecting this to show up under "Scanner" as in the screenshot below.

Have you tried this before? It's a bit hard for me to develop without being able to test during development, so such POS Tester client is helpful.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/12126355/221394819-78c67911-3e0f-4293-a718-5ee8c5cde1b5.png">

**Comment by kvhees** [comment]
There was an issue with the registration in the Registry. I was not using the correct path in OLEForRetail, it seems to be fixed now. 

Thanks for the help!
