### ISSUE TITLE
Difference between ElectronicValueRW and CAT

### ISSUE THREAD

**Issue by kvhees** [kunif/OpenPOS-CSSO#3]

**Comment by kunif** [comment]
Both are devices standardized by the request of the Japanese retail industry.

CAT is the one that handles credit card payments and other processing.
ElectronicValueRW is for electronically storing and carrying things such as cash and points, and making payments within the amount recorded there.

In UPOS 1.15, ElectronicValueRW was specified to integrate CAT functions.
If it is realized as a UPOS 1.15 device, it is better to use ElectronicValueRW.

However, if there is a constraint that it can be realized only with specifications up to POS for.NET 1.14.1, a Hydra device that supports both CAT and ElectronicValueRW in one device would be better.
